apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mongoSecretName }}
type: Opaque
data:
  mongo-root-username: {{ .Values.mongoRootUsername | b64enc }}
  mongo-root-password: {{ .Values.mongoRootPassword | b64enc }}
